name: Publish to GH Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true  # Ensure submodules are checked out

      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'refs/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.deb 'https://github.com/gohugoio/hugo/releases/download/v0.112.4/hugo_extended_0.112.4_linux-amd64.deb'
          sudo dpkg -i /tmp/hugo.deb
          hugo version

      - name: Build
        run: hugo --minify



      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cp -R public/* built-site/
          cd built-site
          git add .
          git config user.name 'ThisUserTaken'
          git config user.email 'hirunadf@gmail.com'
          git commit -m 'Updated site'
          git push
